### ISSUE TITLE
Translation to french

### ISSUE THREAD

**Issue by OpenNingia** [OpenNingia/l5r-character-manager-3#151]
_From [sebdi...@canl.nc](https://code.google.com/u/110525655688021691172/) on February 05, 2013 23:12:20_

I saw there's no french translation... I could try (i won't be alone) but i need markups you use to do proper work...

_Original issue: http://code.google.com/p/l5rcm/issues/detail?id=151_

**Comment by kahlnog** [comment]
Some news about the french core book data pack?
