### ISSUE TITLE
Pdf export not working with non-ascii characters

### ISSUE THREAD

**Issue by OpenNingia** [OpenNingia/l5r-character-manager-3#181]
_From [Yapade...@hotmail.com](https://code.google.com/u/117516496960499148864/) on May 26, 2013 18:02:57_

What steps will reproduce the problem? 1. Building a character
2. Save it
3. Export as pdf What is the expected output? What do you see instead? Its supposed to export as a pdf file yet it doesn't work
The more frustrating is that it worked once !
Just not anymore What version of the product are you using? On what operating system? Windows I use L5RCM 3.7.1 Please provide any additional information below. Here is the exe.log

Traceback (most recent call last):
&nbsp;&nbsp;File "sinks\sink_1.pyc", line 73, in export_character_as_pdf
&nbsp;&nbsp;File "l5rcmcore.pyc", line 220, in export_as_pdf
&nbsp;&nbsp;File "l5rcmcore.pyc", line 175, in _create_fdf
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 39, in export
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 259, in export_body
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 62, in export_field
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 18: ordinal not in range(128)
Traceback (most recent call last):
&nbsp;&nbsp;File "sinks\sink_1.pyc", line 73, in export_character_as_pdf
&nbsp;&nbsp;File "l5rcmcore.pyc", line 220, in export_as_pdf
&nbsp;&nbsp;File "l5rcmcore.pyc", line 175, in _create_fdf
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 39, in export
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 259, in export_body
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 62, in export_field
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 18: ordinal not in range(128)
Traceback (most recent call last):
&nbsp;&nbsp;File "sinks\sink_1.pyc", line 73, in export_character_as_pdf
&nbsp;&nbsp;File "l5rcmcore.pyc", line 220, in export_as_pdf
&nbsp;&nbsp;File "l5rcmcore.pyc", line 175, in _create_fdf
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 39, in export
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 259, in export_body
&nbsp;&nbsp;File "exporters\fdfexporter.pyc", line 62, in export_field
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 18: ordinal not in range(128)

_Original issue: http://code.google.com/p/l5rcm/issues/detail?id=181_

**Comment by shadowkras** [comment]
Im on 3.10.0 and I see three prompts popup and no PDF file is saved.
