### ISSUE TITLE
Mac OSX not working

### ISSUE THREAD

**Issue by JThoreck** [OpenNingia/l5r-character-manager-3#254]
Hello!

I am trying to download what looks like an awesome L5R character manager onto my Mac OS X Yosemite (10.10) and I get the following error when I attempt to open it: Adobe Reader could not open 'L5RCM3.9.1-2.7z' because it is either not a supported file type or because the file has been damaged (for example, it was sent as an email attachment and wasn't correctly decoded).

**Comment by installs** [comment]
I've just unzipped the Mac version OK with 7z and installed v3.9.5 but whenever I try and launch it I get a "l5rcm error" dialog with a nice Terminate button on it...
