### ISSUE TITLE
The app wont launch

### ISSUE THREAD

**Issue by coreblood** [OpenNingia/l5r-character-manager-3#261]
Greetings fellow Rokugani. After I installed the latest version the application just refuses to launch. (win 7 64). The process is initialized and terminated after 2 seconds.﻿ Now even when  I revert back to the old one I get the same problem

**Comment by OpenNingia** [comment]
try to delete the folder "%appdata%\openningia\l5rcm" and try again

**Comment by xmithosx** [comment]
It work for mi, with de new release hotfix... Just testing the rest.
