### ISSUE TITLE
Export pdf stopped working on v3.9.5

### ISSUE THREAD

**Issue by mrmorelo** [OpenNingia/l5r-character-manager-3#263]
I was doing a character, at first the pdf was exporting fine, later it simply didn't create any file in the destined folder.

I did add a new name typed to it, had to edit to personalized things the damage on unamerd atack since the hand of thunder (osano-wo school monk) and Hands of Stone (advantage) wasn't showing in the damage part (or maybe it could only show on the exported pdf, will check and correct if that's the case), and added a 8 line backkground to the char... and when i ask to export, it shows the part where i select the destined folder, and choose a file name, and I click in export, and in the end the file doesn't show up.

once i close the program, this message show up, probably is related:

"The log file'C:\Program Files\OpenNingia\L5CM\l5rcm.exe.log' could not be opened:
[Errno 13] Permission denied:'C:\\Program Files\OpenNingia\L5CM\l5rcm.exe.log'

runnign the program in windows 8.

**Comment by mrmorelo** [comment]
restarted pc, tested in a different character sheet and it worked, opened that character sheet, and it didn't work, if i can send the character sheet file somewhere so you guys can check it i will do.

**Comment by OpenNingia** [comment]
Yes, please upload your character file somewhere ( https://gist.github.com/ is ok, also dropbox or google drive ) and paste a link here.
