### ISSUE TITLE
No Datapacks Installed

### ISSUE THREAD

**Issue by JThoreck** [OpenNingia/l5r-character-manager-3#264]
When I try to open the L5RCM, I get this message:

"No Datapacks Installed
Without data packs the software will be of little use. 
Download a datapack from: https://sourceforge.net/projects/l5rcm/"

However, When I click that link, it just brings me to the download center that downloads the l5rcm. I do not see anything regarding just a datapack. I tried uninstalling the program and reinstalling it directly from that link, I got the same response when I opened the program. 

I am using Version 3.9.5 on a windows 7 computer. Please help!

**Comment by OpenNingia** [comment]
Download datapacks from here: 
http://sourceforge.net/projects/l5rcm/files/Data%20Packs/

Then you can install them either by doubleclick or directly in the program by clicking in the app menu button then on "Import data pack..."
