### ISSUE TITLE
Error Opening file for writing:

### ISSUE THREAD

**Issue by JThoreck** [OpenNingia/l5r-character-manager-3#265]
I downloaded the l5rCM onto my windows 7 machine. When I attempt to install it, I get the following error messages. 

C:\program
Files\OpenNingia\L5RCM\API-MS-Core-LocalRegistry-L1-1-0.dll

Click abort to stop the installation,
Retry to try again, or 
Ignore to skip this file.

I try ignore, and it just gives me similar errors over and over again. Help?

**Comment by OpenNingia** [comment]
Install Visual Studio Redistribuitables from here:
http://www.microsoft.com/en-us/download/details.aspx?id=29
and here:
http://www.microsoft.com/en-us/download/details.aspx?id=5555

and try again.
Let me know if it works.
