### ISSUE TITLE
(In my opinion) the new layout is worst that the old one.

### ISSUE THREAD

**Issue by Kaniabi** [OpenNingia/l5r-character-manager-3#296]
It may have something to do with the change from PySide to PyQt4, but the previous layout, where the character-editor was centered in the window, was better than this one.

Now the character-editor tends to get blued all the way to the bottom.

Maybe it's just something to get used to. What do you think? Was this change o purpose?

**Comment by Kaniabi** [comment]
Funny, but when running it on Development the layout is the old one, that is centered.
Only using the executable that I have the character-editor align to the bottom.

**Comment by OpenNingia** [comment]
@Kaniabi can you please attach a screenshot of the odd layout?

**Comment by Kaniabi** [comment]
I think it was a BUG... that I can't reproduce.
You can close this. I can open again if I found out how to reproduce.
