### ISSUE TITLE
No values are changed by advantages / disadvantages

### ISSUE THREAD

**Issue by xmithosx** [OpenNingia/l5r-character-manager-3#302]
selecting advantages / disadvantages there are values that do not change, for example by selecting the advantage Virtuos the honor rank is not increased by 1

**Comment by OpenNingia** [comment]
@xmithosx 
thanks for the report. These error are mostly not implemented features. In order to be able to fix all those please submit separate issue for each advantage/disadvantage that doesn't behave as expected.
