### ISSUE TITLE
Showing the increment value on wounds total in generated PDF.

### ISSUE THREAD

**Issue by Kaniabi** [OpenNingia/l5r-character-manager-3#303]
The wounds total shows right in the application (10, 14, 18, 22, ...), but shows the wrong values on generated PDF.

For Healthy it shows the 10 (the right value). All the others wound ranks shows the value 4, that I believe is the value of increment for each healthy rank.

**Comment by OpenNingia** [comment]
I just tried and the "Total Wounds" and "Health Left" method are inverted in the UI in respect with the generated PDF.

I.e. when you select "Health Left" from the menu you get a PDF with "Total Wounds" representation and vice versa.
