### ISSUE TITLE
Issues with module? dal and dal.reports.

### ISSUE THREAD

**Issue by Hawk-v3** [OpenNingia/l5r-character-manager-3#305]
After all mentioned prerequisites have been installed, running of the generator's main.py or the datasets make_all_packs.py gets these.

hawk@Cain:~/l5r-character-manager-3/l5r$ python main.py 
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    import api.character
  File "/home/hawk/l5r-character-manager-3/l5r/api/__init__.py", line 19, in <module>
    import dal
ImportError: No module named dal

hawk@Cain:~/l5rcm-data-packs/scripts$ python make_all_packs.py Traceback (most recent call last):
  File "make_all_packs.py", line 22, in <module>
    from dal.report import ContentToMarkDown
ImportError: No module named dal.report

I'm aware I might be missing something, but if I am, googling doesn't give advice for end users, more stuff for people writing programs. I see nothing here about it, either. As this stops all further use, would you mind helping, please?

Thanks for the time.

**Comment by OpenNingia** [comment]
@Hawk-v3 those errors are probably due to the python versions you're using. Are you using Python 3.x ?

L5R:CM support only python 2.7.x interpreters, so if you've python2 installed try running

```bash
python2 main.py
```

**Comment by Hawk-v3** [comment]
hawk@Cain:~$ cd ~/l5rcm-data-packs/scripts/
hawk@Cain:~/l5rcm-data-packs/scripts$ python2 make_all_packs.py Traceback (most recent call last):
  File "make_all_packs.py", line 22, in <module>
    from dal.report import ContentToMarkDown
ImportError: No module named dal.report
hawk@Cain:~/l5rcm-data-packs/scripts$ cd ~/l5r-character-manager-3/l5r/
hawk@Cain:~/l5r-character-manager-3/l5r$ python2 main.py 
Traceback (most recent call last):
  File "main.py", line 31, in <module>
    import api.character
  File "/home/hawk/l5r-character-manager-3/l5r/api/__init__.py", line 19, in <module>
    import dal
ImportError: No module named dal
hawk@Cain:~/l5r-character-manager-3/l5r$ python -V
Python 2.7.9

Apparently, the default version of python on this is 2.7.9, and the results of your suggested commands are above. No change, I'm afraid...

Thank you for your help, it's much appreciated.

**Comment by OpenNingia** [comment]
No problem :) if the python version is correct then the "dal" submodule has not been loaded. Try to run:

```bash
cd ~/l5r-character-manager-3/
git submodule init 
git submodule update
```

If this is the issue I will fix the README file :)

**Comment by Hawk-v3** [comment]
That fixed it, yes!

**Comment by OpenNingia** [comment]
good :+1:  I'll update the README then!
