### ISSUE TITLE
Skills not showing in the first page of PDF

### ISSUE THREAD

**Issue by Kaniabi** [OpenNingia/l5r-character-manager-3#310]
It seems that with the "new" skills page on PDF the skills no longer show up on the PDF first page.

**Comment by OpenNingia** [comment]
The removal was intentional, since skills have a dedicate page it would make sense to remove the skills from the first page. 
Mostly to avoid duplicates but also because we miss a way to select which skills should be printed on the main page if the number of skills exceed the available slots.

**Comment by Kaniabi** [comment]
I understand but I believe that for the majority of cases we could use the skills list on the first page.
What if we only create the skills page if there is too much skills OR we could add an option to create the skills page.

**Comment by OpenNingia** [comment]
That is correct.
I plan to add a dialog to configure the PDF output, as stated in the issue #244

What we need is:

[] a new dialog ( shown upon clicking on Export PDF... )
[] store customization data into QSettings from the dialog
[] read customization data from QSettings from the exporter

**Comment by OpenNingia** [comment]
This is now configurable.
