### ISSUE TITLE
PDF Export Errors in OS X

### ISSUE THREAD

**Issue by neonbasschild** [OpenNingia/l5r-character-manager-3#314]
Ok so I had to a bit of debug to even get pdftk to respond. I placed an alias of pdftk into the tools folder like I normally would and got no permission error. So I place pdftk into the tools folder and started getting errors like shown below. After that I tried to duel approach like what is done with linux. So I changed 

elif sys.platform == 'darwin':
            return os.path.join(MY_CWD, 'tools', 'pdftk')

to

elif sys.platform == 'darwin':
            sys_path = '/usr/bin/pdftk'
            loc_path = os.path.join(MY_CWD, 'tools', 'pdftk')
            if os.path.exists(sys_path):
                return sys_path
            else:
                return loc_path 

I understand that the loc_path is redundant at this point I just wanted to cover all my bases. 

But this is the final error that I got with both /tools/pdftk and /user/bin/pdftk

dyld: Library not loaded: @executable_path/../lib/libgcj.11.dylib
  Referenced from: /usr/bin/pdftk
  Reason: image not found
deleted temp file: /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmp3XJm55.fdf
created pdf /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmpjeZyCZ.pdf
dyld: Library not loaded: @executable_path/../lib/libgcj.11.dylib
  Referenced from: /usr/bin/pdftk
  Reason: image not found
deleted temp file: /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmp73qBOW.fdf
created pdf /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmpEbDj9T.pdf
dyld: Library not loaded: @executable_path/../lib/libgcj.11.dylib
  Referenced from: /usr/bin/pdftk
  Reason: image not found
deleted temp file: /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmplSxe6h.pdf
deleted temp file: /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmpjeZyCZ.pdf
deleted temp file: /var/folders/b5/bt9x5k9n4b13fsvz52rhcjc00000gq/T/tmpEbDj9T.pdf

The only thing that I can think of is that there is some kinda of problem with the pdftk distro at https://www.pdflabs.com/tools/pdftk-server/ or a mismatch between os. I am trying to find some pdftk ports to mac os now. But I could always be barking up the wrong tree.

**Comment by neonbasschild** [comment]
I do remember someone having this error before because they were missing the gcc libraries. I am updating my macports now so that I can try and installing a new version of gcc and see if that fixes anything.

**Comment by OpenNingia** [comment]
@neonbasschild According to this, 

http://stackoverflow.com/questions/2975008/dyld-library-not-loaded-error-mac-os

it could be a path problem.

That executable is looking for `libgcj.11.dylib` in `/usr/lib/`

**Comment by neonbasschild** [comment]
Yeah libgcj.11.dylib is part of gcc4.7 and is a dependency of pdftk that is not included in the package I am trying to find a workable gcc package but all of them that I find fail to compile because of problems with the code and the newer versions of OS X. Still trying to find a work around.

**Comment by OpenNingia** [comment]
did you try building pdftk with this? https://github.com/docmunch/homebrew-pdftk

also I'm looking into a pure python alternative ( PyPDF2 ) but there are blocking issues.
If they could at least fix https://github.com/mstamy2/PyPDF2/issues/232 I could start integrating it.

**Comment by OpenNingia** [comment]
can't support macosx.
