### ISSUE TITLE
Poor UI on higher end laptops

### ISSUE THREAD

**Issue by Ragnatz** [OpenNingia/l5r-character-manager-3#316]
I recently got a new laptop, a Lenovo ideapad Y700, with Windows 10, an Nvidia GeForce GTX 960M, and a native resolution of 3840 x 2160. Loading up L5RCM is resulting in the UI not lining up properly (see attached screenshots)
![l5rcm 1](https://cloud.githubusercontent.com/assets/1192459/12576900/db2e0142-c3cb-11e5-95fb-6a8bd97b1c5d.png)
![l5rcm 2](https://cloud.githubusercontent.com/assets/1192459/12576901/db3031ce-c3cb-11e5-9098-d4c65b963390.png)
![l5rcm 3](https://cloud.githubusercontent.com/assets/1192459/12576902/db325742-c3cb-11e5-8089-1e91f4fd4667.png)

**Comment by Luecian** [comment]
It is an issue I also suffer from and have yet to find a fix but if I do find one I will let you know. I am interested to see if I can work a fix in for it and send the info to the creator.

<img width="960" alt="screenshot 2016-04-13 16 38 56" src="https://cloud.githubusercontent.com/assets/13210198/14508712/cbabacac-0196-11e6-80d9-62e4738b02d5.png">

**Comment by OpenNingia** [comment]
@Luecian can you try this build? https://ci.appveyor.com/api/buildjobs/90kacsd9s1cdui30/artifacts/tools%2Fdeploy%2Fwindows%2FOutput%2Fl5rcm-setup.exe

**Comment by Ragnatz** [comment]
Looks good. I put in a character I made previously and all the columns spread out to fit.
