### ISSUE TITLE
Providing source for PDF template

### ISSUE THREAD

**Issue by obiwankennedy** [OpenNingia/l5r-character-manager-3#324]
I noticed in the source code some PDF template to generate sheet. 
example:
./l5r/share/l5rcm/sheet_npc.pdf

I would like to translate those template but I can't.
It is a simple way to get them ?

**Comment by OpenNingia** [comment]
I'm not the author of that sheet, but you can try asking here: http://emeraldsamurai.com/
Another way would be to buy an (expensive) license of Adobe software that is able to edit PDF.
