### ISSUE TITLE
No Generic Ronin School

### ISSUE THREAD

**Issue by TheHoodedTeddy13** [OpenNingia/l5r-character-manager-3#327]
My GM is letting me select the generic ronin school (an optional rule), but its not there.

**Comment by OpenNingia** [comment]
I'm not working on this software anymore, however we've [a great community on google plus](https://plus.google.com/communities/107752342280671357654) that can help you adding the ronin school to the program.

**Comment by TheHoodedTeddy13** [comment]
Thankyou!
