### ISSUE TITLE
Total failure when saving and exporting to PDF

### ISSUE THREAD

**Issue by phunfoteno2** [OpenNingia/l5r-character-manager-3#346]
Program works fine all throughout the process, but the last milestone is the issue. When either saving the .l5r file or exporting to .pdf, the program crashes and closes. When saving .l5r it creates 0kb files. PDFs not even that. 

Yesterday morning wasn't like that, but midway through my preparations for the evening's session it started acting up. 

[logs.zip](https://github.com/OpenNingia/l5r-character-manager-3/files/7513202/logs.zip)

P.S.: Love this project and been using it for years! Thanks for all your work and hope you guys are still keeping it alive ^^

**Comment by OpenNingia** [comment]
Can you try the latest release?

**Comment by phunfoteno2** [comment]
Latest release works like a charm, thanks!

**Comment by OpenNingia** [comment]
you're welcome :)
