### ISSUE TITLE
New update Will not open program

### ISSUE THREAD

**Issue by SAbel69** [OpenNingia/l5r-character-manager-3#350]
Updated to new version and not the program will not open at all, uninstalled then reinstalled. Now opens but has version 3.12.0 showing not 3.3.14. Still have G+ infor on info page.

**Comment by OpenNingia** [comment]
mh where did you download that?
The new version is here: https://github.com/OpenNingia/l5r-character-manager-3/releases/download/v3.15-3/l5rcm-setup.exe

**Comment by OpenNingia** [comment]
You may also need the latest visual studio redistribuitable: https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by SAbel69** [comment]
Well, now I am back to it not running at all. :( 
I have uninstalled, reinstalled it. used both sites to download material. during installation, it shows as version 3.11.1
Not sure how to handle this 
![image](https://user-images.githubusercontent.com/64493988/153325173-9cc71eb5-2e70-4d57-946d-fead0abcfd81.png)
Attempting to install the visual studio to see if that makes a difference.

**Comment by SAbel69** [comment]
Still can not get it to open not sure why

**Comment by SAbel69** [comment]
is current version 3.14 or 3.15?

**Comment by OpenNingia** [comment]
Ok, I think I found the issue.
Upcoming version is 3.16, i'll update the website asap, in the meantime you can download this:
https://ci.appveyor.com/api/buildjobs/2gi09f99ewfyu49s/artifacts/tools%2Fdeploy%2Fwindows%2FOutput%2Fl5rcm-setup.exe

**Comment by SAbel69** [comment]
3.16.2 works I have also deleted the old Data packs for the new versions. 
On a side note, I have been working with adding the court of the minor clans [NOT Cannon] material if you or others would like to see the files I can work on sending what I have so far.

**Comment by OpenNingia** [comment]
Good. There is still some issue with 3.16.2 which I'm going to fix asap (if you try to export the NPC sheet from the menu then the program will crash :/ ). 

About the minor clans material we could add it to the community pack o create a standalone pack.  submit an issue here: https://github.com/OpenNingia/l5rcm-data-packs and attach your work. I will take a look when I've time.

Thanks :)
