### ISSUE TITLE
There seems to be a typographical error in the .deb package: pdfkt vs pdftk 

### ISSUE THREAD

**Issue by ransage** [OpenNingia/l5r-character-manager-3#356]
I was able to install the downloaded deb by executing the following commands:
```
dpkg-deb -R l5r-character-manager.deb fix-l5r-deb/
sed -i 's/pdfkt/pdftk/' fix-l5r-deb/DEBIAN/control
dpkg-deb -b fix-l5r-deb/ l5r-character-manager-FIXED.deb
```

Then I was able to install l5r-character-manager-FIXED.deb.  If I get a chance, I will upload a fix and create a pull request, but life is pretty hectic right now so no promises that this will be soon.

**Comment by OpenNingia** [comment]
Thanks for your effort, I'll greatly welcome a pull request if you get the time.
